apps/front/forms.py
#编写注册页用户输入信息规范(注册表单)
from wtforms import Form, ValidationError
from wtforms.fields import StringField,IntegerField,FileField #文本字段类，用于处理字符串类型的输入
from wtforms.validators import Email, Length, EqualTo, InputRequired  #验证器
from flask_wtf.file import FileAllowed, FileSize
from models.auth import UserModel
from exts import cache
from flask import request


class BaseForm(Form):
    @property
    def messages(self):
        message_list=[]
        if self.errors:
            for errors in self.errors.values():
                message_list.extend(errors) #extend将errors列表中的元素全部添加到message_list列表中
        return message_list

class RegisterForm(BaseForm):
    #如果使用了Email这个validator,就必须要安装 pip install email_validator
    email = StringField(validators=[Email(message='请输入正确格式的邮箱！')])
    email_captcha = StringField(validators=[Length(6,6,message='请输入正确长度的验证码')]) #最短6位最长6位表示只能输入4位
    username = StringField(validators=[Length(3,20,message='请输入正确长度的用户名')])
    password = StringField(validators=[Length(6,20,message='请输入正确长度的密码')])
    repeat_password = StringField(validators=[EqualTo('password',message='两次输入的密码不一致')])
    graph_captcha = StringField(validators=[Length(4,4,message='请输入正确长度的图形验证码')])

    def validate_email(self,field): #在数据库中检查邮箱是否存在
        #这里函数名必须设置为validate_email，才能通过field.data获取邮箱数据 (validate_对象)
        email = field.data #获取邮箱
        user = UserModel.query.filter_by(email=email).first() #查找数据库中有无该邮箱
        if user:
            raise ValidationError(message='该用户已存在')
    def validate_email_captcha(self,field):
        email_captcha = field.data #获取用户提交的邮箱验证码
        email = self.email.data #获取邮箱
        cache_captcha = cache.get(email) #从缓存里获取发送的验证码
        if not cache_captcha or email_captcha != cache_captcha:
            raise ValidationError(message="邮箱验证码错误")

    def validate_graph_captcha(self,field):
        key = request.cookies.get("_graph_captcha_key") #从cookies中获取图行验证码的键
        cache_captcha = cache.get(key)  #从缓存中取出生成的验证码
        graph_captcha = field.data #获取用户提交的的验证码
        if not cache_captcha or graph_captcha.lower() != cache_captcha.lower():#验证码中有大写有小写，统一全部转成小写以后进行对比
            raise ValidationError(message="图形验证码有误")


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确格式的邮箱！')])
    password = StringField(validators=[Length(6, 20, message='请输入正确长度的密码')])
    remember = IntegerField() #整型，1代表记住，0代表不记住，这个参数可以不传所以不用验证器

class UploadImageForm(BaseForm):
    image = FileField(validators=[FileAllowed(['jpg','jpeg','png'],message="图片格式不符合要求"),
                                  FileSize(max_size=1024*1024*5, message='图片最大不超过5M')])

class EditProfileForm(BaseForm):
    signature = StringField(validators=[Length(1,50,message='个性签名在1到50字之间')])

class PublicPostForm(BaseForm):
    tittle = StringField(validators=[Length(1, 200, message='标题在1到200字之内')])
    board_id = IntegerField(validators=[InputRequired(message="请传入板块id")])
    content = StringField(validators=[InputRequired(message='请输入内容')])

class PublicCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请输入内容')])
    post_id = IntegerField(validators=[InputRequired(message="请传入帖子id")])

apps/front/__init__.py
from .views import bp as front_bp

apps/front/views.py
from flask import Blueprint, request, render_template, jsonify, current_app,make_response,session,redirect,g,jsonify,url_for
import string
import random
from exts import mail
from flask_mail import Message
from exts import cache,db,avatar
from utils import restful
from utils.captcha import Captcha
import time
from hashlib import md5
from io import BytesIO
from .forms import RegisterForm,LoginForm, UploadImageForm, EditProfileForm, PublicPostForm,PublicCommentForm
from models.auth import UserModel,Permission
from models.post import PostModel,BoardModel,BannerModel,CommentModel
from .decorators import login_required
from flask_avatars import Identicon
from flask_paginate import get_page_parameter,Pagination
from sqlalchemy.sql import func
from flask_jwt_extended import create_access_token
import os


#ctel+鼠标左键点击可进入函数内部查看
#通过创建蓝图对象，可以将相关的路由、视图函数和静态文件等组织在一起，以便更好地管理和组织Flask应用程序的功能模块
bp = Blueprint("front",__name__,url_prefix="/") #front是蓝图名称

#####################首页#############################
@bp.route('/')
def index():
    # 根据不同方式排序
    sort = request.args.get("st", type=int, default=1)  # 指定排序方式序号st
    #板块过滤
    boards =BoardModel.query.order_by(BoardModel.priority.desc()).all() #板块名称按优先级从大到小排序
    board_id = request.args.get("bd",type=int,default=None)

    #实现帖子分页
    # flask-paginate参考文档 https://flask-paginate.readthedocs.io/en/master/
    # posts = PostModel.query.order_by(PostModel.create_time.desc()).all()#要分页就不能一次性获取所有帖子
    post_qurey = None

    if sort == 1:
        #按创建时间排序
        post_qurey = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        #按评论数排序涉及到跨表查询
        #将Post和Comment表进行左外连接，并根据post_id进行分组，再更具评论comment_id的数量从大到小进行排序,如果评论数量相同就按照时间排序
        post_qurey=db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(func.count(CommentModel.id).desc(),PostModel.create_time.desc())
    #分页功能的切片头尾
    page = request.args.get(get_page_parameter(), type=int, default=1)
    # p1:0-9 p2:10-19
    start = (page - 1) * current_app.config['PER_PAGE_COUNT']
    end = start + current_app.config['PER_PAGE_COUNT']

    if board_id:
        #有板块id则按照板块id进行过滤
        #当按照评论最多查询时，只让它从postmodel中寻找就可以了，因为sort=2连接了两张表,flask两张表都查，会导致comment表中找不到board_id
        post_qurey=post_qurey.filter(PostModel.board_id==board_id)

    total = post_qurey.count()  # 帖子的总数，Pagination需要传入此参数
    posts = post_qurey.slice(start, end)  # 帖子数量，已切片
    pagination= Pagination(bs_version=3,page=page,total=total,prev_label='上一页',next_label='下一页')

    banners=BannerModel.query.order_by(BannerModel.priority.desc()).all() #获取轮播图数据
    content ={
        "boards":boards,
        "posts":posts,
        #分页
        "pagination":pagination,
        #排序
        "st":sort,
        #分板块
        "bd":board_id,
        #轮播图
        "banners":banners
    }
    return render_template("front/index.html", **content)

#钩子函数：before_request。 在调用front蓝图下的视图函数之前，都会先执行钩子函数
@bp.before_request
def front_before_request():
    if 'user_id' in session:
        user_id = session.get("user_id")#若用户已登录则从session中获取用户id
        user = UserModel.query.get(user_id) #主键可以用get获取
        setattr(g,"user",user) #给user这个全局对象设置一个属性，名为“user”,值为从数据库里获得的user

#请求 => 执行before_request => 若视图函数返回模板 => 执行context_processor => 将context_processor返回的变量也添加到模板中

#上下文处理器
@bp.context_processor
def front_context_processor():
    if hasattr(g,"user"): #检查g中有没有user这个属性
        return {"user": g.user}  #此时这个user已经被渲染到前端的所有的html模板中了
    else:
        return {}

#后台管理页面接口
@bp.get("/cms")
def cms():
    return render_template("cms/index.html")


#####################首页#############################


#####################发布帖子页面#############################
@bp.route("/post/public",methods=['GET', 'POST']) #发布帖子可能使用get/post方法
@login_required
def public_post():
    if request.method == "GET":
        boards = BoardModel.query.order_by(BoardModel.priority.desc()).all()
        return render_template("front/public_post.html",boards=boards)
    else:
        form = PublicPostForm(request.form)
        if form.validate():
            tittle = form.tittle.data
            content = form.content.data
            board_id = form.board_id.data
            try:
                #get 方法：接收一个id作为参数，如果找到了，会返回这条数据
                #如果没找到就抛出异常
                board = BoardModel.query.get(board_id)
            except Exception as e:
                return restful.params_error(message='板块不存在')
            post_model = PostModel(tittle=tittle,content=content,board=board,author=g.user)
            db.session.add(post_model)
            db.session.commit()
            return restful.ok(data={"id":post_model.id})#发布帖子成功后返回帖子id以便跳转到帖子详情页
        else:
            message = form.messages[0]  # 每次只返回第一条错误信息
            return restful.params_error(message=message)



#富文本编辑器上传图片
@bp.post("/post/image/upload")
@login_required
def upload_post_image():
    form = UploadImageForm(request.files) #头像在request.files中
    if form.validate():
        image = form.image.data
        #filename =  image.filename  #不使用用户上传上来的文件名，以防黑客攻击
        filename = image.filename  #form.image.data.filename获取文件名
        _, ext=os.path.splitext(filename) #ext为后缀
        filename =md5((g.user.email+str(time.time())).encode("utf-8")).hexdigest()+ext
        image_path= os.path.join(current_app.config['POST_IMAGE_SAVE_PATH'],filename)
        image.save(image_path)
        return jsonify({
            "errno":0,
            "data":[{
                "url":url_for("media.get_post_image",filename=filename),
                "alt":filename,
                "href":""
            }]})
    else:
        message = form.messages[0]  # 每次只返回第一条错误信息
        return restful.params_error(message=message)

#####################发布帖子页面#############################


#####################帖子详情页面#############################
@bp.get("/post/detail/<int:post_id>")
def post_detail(post_id):
    try:
        post_model = PostModel.query.get(post_id)
    except:
        return "404"
    #获取评论数量
    comment_count =CommentModel.query.filter_by(post_id=post_id).count()
    context = {
        "post":post_model,
        "comment_count":comment_count
    }
    return render_template("front/post_detail.html",**context)
    #return render_template("front/post_detail.html",post=post_model,comment_count=comment_count) 等价于上面那行代码

#评论功能
@bp.post("/comment")
@login_required
def public_comment():
    form = PublicCommentForm(request.form)
    if form.validate():
        content = form.content.data
        post_id = form.post_id.data
        try:
            post_model =PostModel.query.get(post_id)
        except Exception as e:
            return restful.params_error(message='帖子不存在')
        comment = CommentModel(content=content,post_id=post_id,author_id=g.user.id)
        db.session.add(comment)
        db.session.commit()
        return restful.ok()
    else:
        return restful.params_error(message=form.messages[0])
#####################帖子详情页面#############################


#############登录页面###############
@bp.route("/login", methods=['GET','POST'])
def login():
    if request.method == "GET":
        return render_template("front/login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data #这里过来的是用户输入的明文密码
            remember = form.remember.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                return restful.params_error("邮箱或密码错误")
            if not user.check_password(password):
                return restful.params_error("密码错误")
            #运行到此表示验证通过，可登录
            session['user_id']=user.id  #session['user_id']将user_id加密后存入cookie中
            #接下来生成jwt_token以便跨服务器验证，适用于前后端分离项目
            token=""
            permissions=[] #获取用户拥有的权限
            if user.is_staff:
                token=create_access_token(identity=user.id)#如果是员工才生成jwt_token
                #dir(Permission)输出包括自定义的属性和python原本内置的属性  ['ALL_PERMISSION', 'BANNER', 'COMMENT', 'POST', 'STAFF', 'USER', 'VISITOR', '__class__', '__delattr__'......]
                for per in dir(Permission):
                    if not per.startswith("_"): #不以_开头的都是自定义的权限
                        permission=getattr(Permission,per) #取出其中一个权限的值
                        if user.has_permission(permission):
                            permissions.append(per.lower())
            if remember == 1:
                #默认session过期时间，就是浏览器关闭了就会过期
                session.permanent =True #勾选了记住则延后session的过期时间，过期时间需要在config中配置

            user_dict=user.to_dict()
            user_dict['permissions']=permissions

            return restful.ok(data={"token":token, "user":user_dict}) #SerizlizerMixin会给ORM模型添加一个to_dict方法  user.to_dict()返回的信息会包括与user相关的引用的信息，会造成资源浪费
        else:
            return restful.params_error(message=form.messages[0])

##退出登录视图
@bp.route("/logout")
def logout():
    session.clear() #将登录状态写入的session清空
    return redirect("/")

#############登录页面###############


######################注册页面########################
@bp.route("/register", methods=['GET','POST'])
def register():
    if request.method == "GET":
        return render_template("front/register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate(): #若用户注册信息通过了验证表单
            email = form.email.data
            username = form.username.data
            password = form.password.data
            #标识生成法生成头像
            identicon = Identicon() #创建 Identicon 类的实例
            fileames = identicon.generate(text=md5(email.encode("utf-8")).hexdigest()) #直接用加密后的邮箱作为头像名称
            avatar = fileames[2] #这是头像尺寸，详见参考文档https://zlkt.net/post/detail/59
            user = UserModel(email=email,username=username,password=password,avatar=avatar)
            db.session.add(user)
            db.session.commit()
            return restful.ok()
        else:
            # form.errors中存放了所有的错误信息
            #print(form.errors)

templates/front/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}"> {# 编写register的Ajax请求时添加因为发送邮件需要使用post方法 #}
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{url_for('static', filename = 'front/js/zlajax.js')}}"></script> {# 通过url_for()指向对应基础js文件 #}
    <script src="{{url_for('static', filename = 'front/js/zlparam.js')}}"></script>
    <link rel="stylesheet" href="{{url_for('static',filename ='front/css/front_base.css')}}">{# 通过url_for()指向对应基础css文件 #}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>> {# 各个页面各自的标题 #}
    {% block head %}{% endblock %}{# 各个页面各自需要指向的文件，js或css这些的 #}{# base模板中只保留大家都有的，其它页面的css文件以及js文件在各自的html中指定 #}
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Python论坛</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="请输入关键字">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {# 导航条登录/非登录状态切换 #}
                    {% if user %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                {{ user.username }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a href="{{url_for('front.cms')}}">后台管理</a></li>
                                <li><a href="{{url_for('front.setting')}}">设置</a></li>
                                <li><a href="{{url_for('front.logout')}}">注销</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{url_for('front.login')}}">登录</a> </li>
                        <li><a href="{{url_for('front.register')}}">注册</a> </li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="main-container">
        {% block body %}{# 中间这块就是大家都不一样的东西了 #}
        {% endblock %}
    </div>
</body>

</html>

templates/front/index.html
{% extends "front/base.html" %}
{% block title %}
    首页
{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='front/css/index.css') }}">
{% endblock %}
{% block body %}
<div class="lg-container">
<div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
  <!-- 指示器 -->
  <ol class="carousel-indicators">
      {% for banner in banners %}
          {% if loop.first %}
        <li data-target="#carousel-example-generic" data-slide-to="{{ loop.index0 }}" class="active"></li>{# index0 表示下标从0开始 #}
          {% else %}
          <li data-target="#carousel-example-generic" data-slide-to="{{ loop.index0 }}" ></li>
          {% endif %}
      {% endfor %}
  </ol>
  <!-- 轮播图 -->
  <div class="carousel-inner" role="listbox">
      {% for banner in banners %}
        {% if loop.first %}
      <div class="item active"> {# 只激活第一个轮播图 #}
        {% else %}
          <div class="item">
        {% endif %}
        <a href="{{ banner.link_url }}" target="_blank">
          <img src="{{banner.image_url}}" alt="{{banner.name}}"> {# alt="{{banner.name}}" 表示轮播图失效以后展示轮播图名称 #}
        </a>
      </div>
      {% endfor %}
  </div>

    <!-- 左右切换的控制按钮 -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<div class="post-group">
  <ul class="post-group-head">
      {% if st ==1 %}
      <li class="active">
      {% else %}
      <li>
      {% endif %}
          <a href="{{url_for('front.index',st=1,bd=bd)}}">最新</a>
      </li>

      {% if st ==2 %}
        <li class="active">
      {% else %}
        <li>
      {% endif %}
          <a href="{{url_for('front.index',st=2,bd=bd)}}">评论最多</a>
      </li>
  </ul>
  <ul class="post-list-group">
      {% for post in posts %}
      <li>
        <div class="author-avatar-group">
          <img src="{{url_for('media.get_avatar', filename=post.author.avatar)}}" alt="">
        </div>
        <div class="post-info-group">
          <p class="post-title">
            <a href="{{ url_for('front.post_detail',post_id=post.id) }}">{{post.tittle}}</a>
          </p>
          <p class="post-info">
            <span>作者：{{post.author.username}}</span>
            <span>发表时间：{{ post.create_time}}</span>
            <span>评论:{{ post.comments|length }}</span>
          </p>
        </div>
      </li>
      {% endfor %}
  </ul>
    <div style="text-align: center">
        {{ pagination.links }}
    </div>
</div>
</div>
<div class="sm-container">
<div style="padding-bottom:10px;">
  <a href="{{ url_for('front.public_post') }}" class="btn btn-warning btn-block">发布帖子</a>
</div>
<div class="list-group">
    {% if bd %}
    <a href="/" class="list-group-item">所有板块</a> {# 板块列表 #}
    {% else %}
    <a href="/" class="list-group-item active">所有板块</a> {# 板块列表 #}
    {% endif %}
    {% for board in boards %}
        {% if bd ==board.id %}
        <a href="{{url_for("front.index",bd=board.id, page=1)}}" class="list-group-item active">
        {% else %}
        <a href="{{url_for("front.index",bd=board.id, page=1)}}" class="list-group-item ">
        {% endif %}
            {{ board.name }}
        </a>{# page=1参数让板块切换时回到第一页 #}
    {% endfor %}
</div>
</div>
{% endblock %}

templates/front/login.html
{% extends "front/base.html" %}
{% block title %}
    登录
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='front/css/signbase.css') }}">
    <script src="{{ url_for('static',filename='front/js/login.js') }}"> </script>
{% endblock %}
{% block body %}
    <div class="outer-box">
            <div class="logo-box">
                <a href="/">
                    <img src="{{url_for('static',filename = 'front/images/logo.png')}}" alt="">
                </a>
            </div>
            <h2 class="page-title">
                登录
            </h2>
            <div class="sign-box">
                <div class="form-group">
                    <input type="text" class="form-control" name="email" placeholder="邮箱">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="密码">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="remember" value="1">记住我
                    </label>
                </div>
                <div class="form-group">
                    <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
                </div>
                <div class="form-group">
                    <a href="#" class="signup-link">没有账号？立即注册</a>
                    <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
                </div>
            </div>
        </div>
{% endblock %}

templates/front/post_detail.html
{% extends "front/base.html" %}
{% block tittle %}
{{ post.tittle }}
{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='lib/highlight/styles/default.min.css') }}">
<script src="{{ url_for('static', filename='lib/highlight/highlight.min.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static',filename='front/css/post_detail.css') }}">
<script src="{{ url_for('static', filename='front/js/post_detail.js') }}"></script>
{% endblock %}
{% block body %}
<div class="post-container">
  <h2>{{post.tittle}}</h2>
  <p class="post-info-group">
    <span>发表时间：{{ post.create_time }}</span>
    <span>作者：{{post.author.usaername}}</span>
    <span>所属板块：{{ post.board.name }}</span>
    <span>评论数：{{ comment_count }}</span>
  </p>
    <div class="post-content">
        {{ post.content|safe }}
    </div>
</div>
<div class="comment-group">
  <h3>评论列表</h3>
  <ul class="comment-list-group">
      {% for comment in post.comments %}
    <li>
      <div class="avatar-group">
        <img src="{{url_for('media.get_avatar',filename=comment.author.avatar)}}" alt="">
      </div>
      <div class="comment-content">
        <p class="author-info">
          <span>{{ comment.author.username }}</span>
          <span>{{ comment.create_time}}</span>
        </p>
        <p class="comment-txt">
            {{comment.content}}
        </p>
      </div>
    </li>
      {% endfor %}
  </ul>
</div>
<div class="add-comment-group">
  <h3>发表评论</h3>
  <textarea name="comment" id="comment-textarea" style="width: 100%; resize:vertical;"></textarea>
  <div class="comment-btn-group">
    <button class="btn btn-primary" id="comment-btn" data-post-id ="{{ post.id }}" data-user-id ="{{ user.id }}">发表评论</button>
  </div>
</div>
{% endblock %}

templates/front/post_detail_belike.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>帖子详情</title>
</head>
<body>
<h1>{{ post.tittle }}</h1>
</body>
</html>

templates/front/public_post.html
{% extends "front/base.html" %}
{% block title %}
    发布帖子
{% endblock %}
{% block head %}
    <script src="{{ url_for('static', filename='lib/wangEditor/wangEditor.min.js') }}"></script>
    <script src="{{ url_for('static', filename='front/js/public_post.js') }}"></script>
{% endblock %}
{% block body %}
<h1 style="text-align: center; padding: 20px;">发布帖子</h1>
<form action="" method="post">
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">标题</span>
      <input type="text" class="form-control" name="title">
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">板块</span>
      <select name="board_id" class="form-control">
          {% for board in boards %}
              <option value="{{ board.id }}">{{ board.name }}</option> {# 服务器按照value的值来判断使用哪个板块 #}
          {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group">
      <div id="editor"></div>
  </div>
  <div class="form-group">
    <button class="btn btn-danger" id="submit-btn">发布帖子</button>
  </div>
</form>
{% endblock %}

templates/front/register.html
{% extends 'front/base.html' %}
{% block title %}
    注册
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='front/css/signbase.css') }}">
    <script src="{{ url_for('static', filename='front/js/register.js') }}"></script>>
{% endblock %}
{% block body %}
    <div class="outer-box">
            <div class="logo-box">
                <a href="/">
                    <img src="{{url_for('static',filename = 'front/images/logo.png')}}" alt="">
                </a>
            </div>
            <h2 class="page-title">
                注册
            </h2>
            <div class="sign-box">
                <div class="form-group">
                    <div class="input-group">
                        <input type="email" class="form-control" name="email" placeholder="邮箱">
                        <span class="input-group-btn">
                            <button id="email-captcha-btn" class="btn btn-default">发送验证码</button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="email-captcha" placeholder="邮箱验证码">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="用户名">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="密码">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="repeat-password" placeholder="确认密码">
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" name="graph-captcha" placeholder="图形验证码">
                        <span class="input-group-addon captcha-addon">
                            <img id="captcha-img" class="captcha-img" src="{{ url_for('front.graph_captcha') }}" alt="">
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
                </div>
            </div>
        </div>
{% endblock %}

templates/front/setting.html
{% extends "front/base.html" %}
{% block title %}个人设置{% endblock %}
{% block head %}
    <script src="{{ url_for('static', filename='front/js/setting.js') }}"></script>>
    <link rel="stylesheet" href="{{url_for("static",filename="front/css/index.css")}}">
    <style>
    body{
      background-color: #f3f3f3;
    }
    .setting-group {
      width: 800px;
      background-color: #ffffff;
      margin: 0 auto;
      padding: 50px;
    }
    #avatar-img{
      width: 140px;
      height: 140px;
    }
  </style>
{% endblock %}
{% block body %}
<div class="setting-group">
      <h1>{{ user.username }}设置</h1>
      <div style="height: 20px;"></div>
      <form>
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱：</label>
          <input type="email" class="form-control" value="{{ user.email }}" readonly>
        </div>
        <div class="form-group">
          <label>头像：</label>
          <div class="input-group">
              {#<img src="{{avatars.gravatar(email_hash)}}" alt="..." class="img-circle" id="avatar-img"> #}
            <img src="{{url_for('media.get_avatar',filename=user.avatar)}}" alt="..." class="img-circle" id="avatar-img">
            <input type="file" id="avatar-input" accept="image/jpeg, image/png">
          </div>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">个性签名：</label>
          <input type="text" class="form-control" id="signagure-input" value="{{ user.signature or ""}}">
        </div>
        <button type="submit" id="submit-btn" class="btn btn-primary">保存</button>
      </form>
    </div>
{% endblock %}